### ISSUE TITLE
error: no member named 'abs' in namespace 'std'

### ISSUE THREAD

**Issue by sjackman** [isovic/racon#20]
Racon fails to compile with clang 800.0.42.1 on MacOS 10.11.6.

Note that `libc++` unexpectedly defines `std::abs(float)` in `cmath` and `std::abs(int)` in `cstdlib`.
See http://en.cppreference.com/w/cpp/numeric/math/abs

Error
```
codebase/seqlib/src/libs/opal.cc:1304:45: error: no member named 'abs' in namespace 'std'; did you mean simply 'abs'?
```

Fix
```diff
diff --git a/private/tmp/racon-20170222-8113-p8dp0x/racon-v0.5.0/codebase/seqlib/src/libs/opal.cc.orig b/private/tmp/racon-20170222-8113-p8dp0x/racon-v0.5.0/codebase/seqlib/src/libs/opal.cc
index f819e6db..0636bae6 100644
--- a/codebase/seqlib/src/libs/opal.cc
+++ b/codebase/seqlib/src/libs/opal.cc
@@ -20,6 +20,7 @@
 #include <algorithm>
 #include <cassert>
 #include <climits>
 #include <cstdio>
+#include <cstdlib>
 #include <limits>
 #include <vector>
```

**Comment by isovic** [comment]
Hi Shaun!

I updated this now, thanks!
Pushed to master.
Don't forget to run ```make modules``` before ```make```.
I'll package a new release as soon I address the other issue.

Thanks again!
Best regards,
Ivan.

**Comment by sjackman** [comment]
Thanks for your quick response, Ivan!
No need to rush for a release. This bug only affects `clang`, and Apple `clang` doesn't support OpenMP, so I'm building it with `gcc` now.

**Comment by rvaser** [comment]
Racon 1.0.0 has now clang support (although, tested only on Linux distributions).

**Comment by sjackman** [comment]
Great! I'll package Racon 1.0.0 for Homebrew/Linuxbrew.
